
service: esme-pump-connector # NOTE: update this with your service name

plugins:
  - serverless-offline

package:
  exclude:
    - .vscode/**
    - aws-functions/**
    - tests/**

custom:
  stage: ${opt:stage, 'dev'}
  version: "1.0"

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: ${self:custom.stage}
  region: us-east-1
  #profile: CodeStarWorker-test-ToolChain
  #VPC for all lambdas
  #vpc:
  #    securityGroupIds: 
  #      - ${ssm:/${self:custom.stage}/sme/rds/LambdaSecurityGroup}
  #    subnetIds: { Fn::Split: [ ",", "${ssm:/${self:custom.stage}/sme/vpc/PrivateSubnetsList}" ] }

# be careful, this will route every HTTP event to your function.
functions:
  - ${file(aws-functions/entity.yml)}